server:
  port: 9999

spring:
  datasource:
    username: root
    password: crush
    url: >
            jdbc:mysql://localhost:3306/easyexcel_universal_listener?
            useSSL=true&
            useUnicode=true&
            characterEncoding=UTF-8&
            useTimezone=true&
            serverTimezone=GMT%2B8&
            allowMultiQueries=true&
            rewriteBatchedStatements=true
    hikari:
      # 要保证 UniversalListener 监听器中的回滚有效果. 这个值设置为 false 也不会影响事物自动提交, 这是为什么?
      # https://stackoverflow.com/questions/64502965/hikaricp-makes-commit-despite-isautocommit-false
      auto-commit: false
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    # MyBatis 核心配置文件中设置的执行器类型, 默认是 simple.
    default-executor-type: batch
  mapper-locations: classpath:indi/ly/crush/mapper/xml/I*Mapper.xml
  # SqlSessionTemplate 使用的执行器类型
  executor-type: batch